name: "Criação de nova Funcionalidade"
description: "funcionalidade para o projeto."
title: "[FEATURE]: "
labels: ["feature", "precisa-triagem"]
body:
  - type: markdown
    attributes:
      value: |
        Descreva a funcionalidade proposta em detalhes.

  - type: markdown
    id: o-que-deve-ser-feito
    attributes:
      label: "O que deve ser feito? (Checklist)"
      description: "Liste as principais tarefas, requisitos ou critérios de aceite para esta funcionalidade."
      placeholder: |
        - [ ] Tarefa 1
        - [ ] Tarefa 2
        - [ ] Critério de aceite X
    validations:
      required: true
